version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_AUTOVACUUM_ANALYZE_SCALE_FACTOR: '0.05'
      POSTGRES_AUTOVACUUM_VACUUM_SCALE_FACTOR: '0.1'
      POSTGRES_LOGGING: 'json'
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_SSL_MODE: require
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g

volumes:
  pgdata:
