{
 "title": "Streets11",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "# Accepted Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(public.street.length_int) AS accepted_street_count FROM public.street WHERE public.street.length_int > 0 "
    }
   ]
  },
  {
   "title": "# UnAccepted Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(public.street.unaccepted_length_int) AS unaccepted_street_count FROM public.street WHERE public.street.unaccepted_length_int > 0 "
    }
   ]
  },
  {
   "title": "Street Widths",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT width_int FROM street WHERE noncity <> 'X' and width_int > 0"
    }
   ]
  },
  {
   "title": "Width > 40 Streets6",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.length_int) AS accepted_length_sum_feet FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int >= 40 "
    }
   ]
  },
  {
   "title": "Width > 50 Streets7",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.length_int) AS accepted_length_sum_feet FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int >= 50 "
    }
   ]
  },
  {
   "title": "Width > 60 Streets8",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.length_int) AS accepted_length_sum_feet FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int >= 60 "
    }
   ]
  },
  {
   "title": "Total Length Streets12",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.length_int + public.street.unaccepted_length_int) AS total_length_sum_feet FROM public.street "
    }
   ]
  },
  {
   "title": "Accepted Streets1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.length_int) AS accepted_length_sum_feet FROM public.street WHERE public.street.length_int > 0 "
    }
   ]
  },
  {
   "title": "UnAccepted Streets2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.unaccepted_length_int) AS unaccepted_length_sum_feet FROM public.street WHERE public.street.unaccepted_length_int > 0 "
    }
   ]
  },
  {
   "title": "Width > 40 Streets9",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(public.street.length_int) / 5280.0, 2) AS accepted_length_sum_miles FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int >= 40 "
    }
   ]
  },
  {
   "title": "Width > 50 Streets10",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(public.street.length_int) / 5280.0, 2) AS accepted_length_sum_miles FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int >= 50 "
    }
   ]
  },
  {
   "title": "Width > 60 Streets11",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(public.street.length_int) / 5280.0, 2) AS accepted_length_sum_miles FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int >= 60 "
    }
   ]
  },
  {
   "title": "Length by Street Widths",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT width_int, sum(length_int) as sum_length FROM street WHERE noncity <> 'X' and width_int > 0 and length_int > 0 group by width_int"
    }
   ]
  },
  {
   "title": "Total Length Streets13",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(public.street.length_int + public.street.unaccepted_length_int) / 5280.0, 2) AS total_length_sum_miles FROM public.street "
    }
   ]
  },
  {
   "title": "Accepted Streets4",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(public.street.length_int) / 5280.0, 2) AS accepted_length_sum_miles FROM public.street WHERE public.street.length_int > 0 "
    }
   ]
  },
  {
   "title": "UnAccepted Streets5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(public.street.unaccepted_length_int) / 5280.0, 2) AS unaccepted_length_sum_miles FROM public.street WHERE public.street.unaccepted_length_int > 0 "
    }
   ]
  },
  {
   "title": "Total Area Streets16",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "areaMI2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND((SUM((public.street.length_int + public.street.length_int) * public.street.width_int) / 27878400.0), 2) AS total_area_sq_miles FROM public.street "
    }
   ]
  },
  {
   "title": "Accepted Area17",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "areaMI2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND((SUM(public.street.length_int * public.street.width_int) / 27878400.0), 2) AS accepted_area_sq_miles FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int > 0 "
    }
   ]
  },
  {
   "title": "UnAccepted Area18",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "areaMI2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND((SUM(public.street.unaccepted_length_int * public.street.width_int) / 27878400.0), 2) AS unaccepted_area_sq_miles FROM public.street WHERE public.street.unaccepted_length_int > 0 AND public.street.width_int > 0; "
    }
   ]
  },
  {
   "title": "Total Sum Width19",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.width_int) AS total_width_sum_feet FROM public.street "
    }
   ]
  },
  {
   "title": "Sum Accepted Width20",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.width_int) AS accepted_length_sum_feet FROM public.street WHERE public.street.length_int > 0 AND public.street.width_int > 0 "
    }
   ]
  },
  {
   "title": "Sum UnAccepted Width21",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(public.street.width_int) AS unaccepted_length_sum_feet FROM public.street WHERE public.street.unaccepted_length_int > 0 AND public.street.width_int > 0 "
    }
   ]
  }
 ]
}