{
 "title": "Streets10",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "# Accepted Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street WHERE length IS NOT NULL LIMIT 50 "
    }
   ]
  },
  {
   "title": "# UnAccepted Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street WHERE length IS NULL LIMIT 50 "
    }
   ]
  },
  {
   "title": "Street Width14",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(width) FROM street GROUP BY width LIMIT 50 "
    },
    {
     "rawSql": "SELECT COUNT(width) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "Width > 40 Streets6",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) AS accepted_length_sum FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 AND CAST(regexp_replace(width, '\\D', '', 'g') AS INTEGER) >= 40 "
    }
   ]
  },
  {
   "title": "Width > 50 Streets7",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) AS accepted_length_sum FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 AND CAST(regexp_replace(width, '\\D', '', 'g') AS INTEGER) >= 50 "
    }
   ]
  },
  {
   "title": "Width > 60 Streets8",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) AS accepted_length_sum FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 AND CAST(regexp_replace(width, '\\D', '', 'g') AS INTEGER) >= 60 "
    }
   ]
  },
  {
   "title": "Total Length Streets12 BAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 0; " }
   ]
  },
  {
   "title": "Accepted Streets1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) AS accepted_length_sum FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 "
    }
   ]
  },
  {
   "title": "UnAccepted Streets2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(regexp_replace(unacceptedlength, '\\D', '', 'g') AS INTEGER)) AS unaccepted_length_sum FROM street WHERE CAST(regexp_replace(unacceptedlength, '\\D', '', 'g') AS INTEGER) > 0 "
    }
   ]
  },
  {
   "title": "Width > 40 Streets9",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) / 5280.0, 2) AS accepted_length_sum_miles FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 AND CAST(regexp_replace(width, '\\D', '', 'g') AS INTEGER) >= 40 "
    }
   ]
  },
  {
   "title": "Width > 50 Streets10",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) / 5280.0, 2) AS accepted_length_sum_miles FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 AND CAST(regexp_replace(width, '\\D', '', 'g') AS INTEGER) >= 50 "
    }
   ]
  },
  {
   "title": "Width > 60 Streets11",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) / 5280.0, 2) AS accepted_length_sum_miles FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 AND CAST(regexp_replace(width, '\\D', '', 'g') AS INTEGER) >= 60 "
    }
   ]
  },
  {
   "title": "Total Length Streets13 BAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 0; " }
   ]
  },
  {
   "title": "Accepted Streets4",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER)) / 5280.0, 1) AS accepted_length_sum_miles FROM street WHERE CAST(regexp_replace(length, '\\D', '', 'g') AS INTEGER) > 0 "
    }
   ]
  },
  {
   "title": "UnAccepted Streets5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ROUND(SUM(CAST(regexp_replace(unacceptedlength, '\\D', '', 'g') AS INTEGER)) / 5280.0, 1) AS unaccepted_length_sum_miles FROM street WHERE CAST(regexp_replace(unacceptedlength, '\\D', '', 'g') AS INTEGER) > 0 "
    }
   ]
  },
  {
   "title": "Accepted by Year15",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(width) FROM street GROUP BY width LIMIT 50 "
    },
    {
     "rawSql": "SELECT COUNT(width) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Area Streets16 BAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "areaMI2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 0; " }
   ]
  },
  {
   "title": "Accepted Area17 Maybe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "areaMI2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(REGEXP_REPLACE(length, '\\D', '', 'g') AS FLOAT) * CAST(REGEXP_REPLACE(width, '\\D', '', 'g') AS FLOAT) / 27878400) AS accepted_area_sum_sq_mi FROM street WHERE CAST(REGEXP_REPLACE(length, '\\D', '', 'g') AS FLOAT) > 0 AND CAST(REGEXP_REPLACE(width, '\\D', '', 'g') AS FLOAT) > 0 "
    }
   ]
  },
  {
   "title": "UnAccepted Area18 BAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "areaMI2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 0; " }
   ]
  },
  {
   "title": "Total Sum Width19 BAD",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 0; " }
   ]
  },
  {
   "title": "Sum Accepted Width20",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(CAST(regexp_replace(public.street.width, '\\D', '', 'g') AS INTEGER)) AS accepted_width_feet FROM  street WHERE CAST(regexp_replace(public.street.length, '\\D', '', 'g') AS INTEGER) > 0 AND   CAST(REGEXP_REPLACE(public.street.width, '\\D', '', 'g') AS FLOAT) > 0 AND   CAST(REGEXP_REPLACE(public.street.width, '\\D', '', 'g') AS FLOAT) < 150; "
    }
   ]
  },
  {
   "title": "Sum UnAccepted Width21",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 0 " }
   ]
  }
 ]
}