{
 "title": "Streets3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "# Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "# Accepted Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street WHERE length IS NOT NULL LIMIT 50 "
    }
   ]
  },
  {
   "title": "# UnAccepted Streets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street WHERE length IS NULL LIMIT 50 "
    }
   ]
  },
  {
   "title": "Accepted Streets1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "UnAccepted Streets2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "Streets3",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "Street Width",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(width) FROM street GROUP BY width LIMIT 50 "
    },
    {
     "rawSql": "SELECT COUNT(width) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "Accepted Streets4",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  },
  {
   "title": "UnAccepted Streets5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM street LIMIT 50 "
    }
   ]
  }
 ]
}